name: 'Trigger CircleCI Pipeline with Configurable Inputs'
description: 'Trigger pipelines on CircleCI for any event on GitHub.'
branding:
    icon: "check-circle"
    color: "green"
inputs:
  GHA_Meta:
    required: false
    description: 'An optional additional JSON metadata parameter. Every key in the provided JSON will be available on the CircleCI pipeline as a parameter'
runs:
  using: 'node16'
  main: 'dist/index.js'
